In [1]:
import torch

# 张量的拼接与切分

## 1.torch.cat()
## 功能：将张量按维度拼接

In [2]:
t = torch.ones(2,3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.cat([t,t],dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.cat([t,t],dim=1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

## 2.torch.stack()
## 功能：在新创建的维度上拼接

In [8]:
torch.stack([t,t],dim=2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

## 3.torch.chunk()
## 功能：将张量按维度dim平均切分,不能整除的话，最后一个相量大小会与其他向量不同

In [11]:
t = torch.ones(5,7)
t

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [12]:
tensor_list = t.chunk(chunks = 3 , dim = 1)
for tensor in tensor_list:
    print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [13]:
tensor_list = t.chunk(chunks = 3 , dim = 0)
for tensor in tensor_list:
    print(tensor)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1.]])


## 4.torch.split()
## 功能：另一种切分

In [14]:
t

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
torch.split(t,2,dim=0)

(tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]), tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]), tensor([[1., 1., 1., 1., 1., 1., 1.]]))

In [17]:
torch.split(t,[1,1,3],dim=0)

(tensor([[1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]))

# 张量索引

## torch.index_select()
## 功能：在维度dim上，按照索引index进行数据拼接

In [19]:
t = torch.randint(0,9,size=(3,3))
t

tensor([[3, 4, 1],
        [2, 4, 1],
        [2, 1, 3]])

In [21]:
index = torch.tensor([0,1],dtype=torch.long) #类型必须是long
index

tensor([0, 1])

In [24]:
torch.index_select(t,index=index,dim=0)

tensor([[3, 4, 1],
        [2, 4, 1]])

## torch.masked_select()
## 功能：根据mask判断True或False，返回一维数组

In [25]:
t

tensor([[3, 4, 1],
        [2, 4, 1],
        [2, 1, 3]])

In [30]:
mask = t.ge(2)   # 创建大于等于5的mask,gt ge lt le 分别是＞ ≥ ＜ ≤
mask

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True, False,  True]])

In [31]:
torch.masked_select(t,mask)

tensor([3, 4, 2, 4, 2, 3])

# 张量变换

## torch.reshape()
## 功能：改变张量形状，两张量共用内存

In [32]:
t

tensor([[3, 4, 1],
        [2, 4, 1],
        [2, 1, 3]])

In [35]:
torch.reshape(t,shape=(1,9))

tensor([[3, 4, 1, 2, 4, 1, 2, 1, 3]])

In [36]:
torch.reshape(t,shape=(9,-1))  # -1的意思是程序运算

tensor([[3],
        [4],
        [1],
        [2],
        [4],
        [1],
        [2],
        [1],
        [3]])

## torch.transpose()
## 功能：张量交换维度

In [37]:
t

tensor([[3, 4, 1],
        [2, 4, 1],
        [2, 1, 3]])

In [39]:
torch.transpose(t,0,1)

tensor([[3, 2, 2],
        [4, 4, 1],
        [1, 1, 3]])

## torch.t()
## 功能：张量转置

In [40]:
torch.t(t)

tensor([[3, 2, 2],
        [4, 4, 1],
        [1, 1, 3]])

## torch.squeeze()
## 功能：移除张量长度为一的维度

In [44]:
t = torch.rand(1,2,3,4,1)

In [48]:
t1 = torch.squeeze(t)
t1.shape

torch.Size([2, 3, 4])

## torch.unsqueeze()
## 功能：新增加一个维度

In [52]:
torch.unsqueeze(t,dim=0).shape

torch.Size([1, 1, 2, 3, 4, 1])

# 张量数学运算

## 加减乘除

torch.add()
torch.addcdiv()
torch.addcmul()
torch.sub()
torch.div()
torch.mul()

## 指数

In [ ]:
torch.log()
torch.log10()
torch.log2()
torch.exp()
torch.pow()

## 三角函数

In [ ]:
torch.abs()
torch.acos()
torch.cosh()
torch.cos()
torch.asin()
torch.atan()
torch.atan2()